-- OmniRoute PostgreSQL baseline for Supabase.
-- This is the first domain slice, not a complete translation of OmniRoute's
-- 100+ SQLite migrations. Keep this migration additive and idempotent.
-- Apply via Supabase SQL migrations after reviewing the target project.
--
-- Values such as timestamps and JSON blobs intentionally remain TEXT initially
-- to preserve compatibility with the current SQLite serialization format.
-- Incremental domain migrations will tighten types after callers are ported.

CREATE TABLE IF NOT EXISTS public.provider_connections (
  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  auth_type TEXT,
  name TEXT,
  email TEXT,
  priority INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  access_token TEXT,
  refresh_token TEXT,
  expires_at TEXT,
  token_expires_at TEXT,
  scope TEXT,
  project_id TEXT,
  test_status TEXT,
  error_code TEXT,
  last_error TEXT,
  last_error_at TEXT,
  last_error_type TEXT,
  last_error_source TEXT,
  backoff_level INTEGER NOT NULL DEFAULT 0,
  rate_limited_until TEXT,
  health_check_interval INTEGER,
  last_health_check_at TEXT,
  last_tested TEXT,
  api_key TEXT,
  id_token TEXT,
  provider_specific_data TEXT,
  expires_in INTEGER,
  display_name TEXT,
  global_priority INTEGER,
  default_model TEXT,
  token_type TEXT,
  consecutive_use_count INTEGER NOT NULL DEFAULT 0,
  rate_limit_protection INTEGER NOT NULL DEFAULT 0,
  last_used_at TEXT,
  rate_limit_overrides_json TEXT,
  last_ping_at TEXT,
  last_pinged_reset_key TEXT,
  "group" TEXT,
  max_concurrent INTEGER,
  proxy_enabled INTEGER NOT NULL DEFAULT 1,
  per_key_proxy_enabled INTEGER NOT NULL DEFAULT 0,
  quota_visible INTEGER NOT NULL DEFAULT 1,
  quota_window_thresholds_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pc_provider ON public.provider_connections(provider);
CREATE INDEX IF NOT EXISTS idx_pc_active ON public.provider_connections(is_active);
CREATE INDEX IF NOT EXISTS idx_pc_priority ON public.provider_connections(provider, priority);
CREATE INDEX IF NOT EXISTS idx_pc_max_concurrent ON public.provider_connections(provider, max_concurrent);
CREATE INDEX IF NOT EXISTS idx_pc_auth_active_refresh ON public.provider_connections(auth_type, is_active, refresh_token);
CREATE INDEX IF NOT EXISTS idx_pc_provider_auth_type ON public.provider_connections(provider, auth_type);

CREATE TABLE IF NOT EXISTS public.provider_nodes (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  prefix TEXT,
  api_type TEXT,
  base_url TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.key_value (
  namespace TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  PRIMARY KEY (namespace, key)
);

CREATE TABLE IF NOT EXISTS public.combos (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  data TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.api_keys (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  key TEXT NOT NULL UNIQUE,
  machine_id TEXT,
  model_access_mode TEXT,
  allowed_models TEXT,
  no_log INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ak_key ON public.api_keys(key);

CREATE TABLE IF NOT EXISTS public.db_meta (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS public.usage_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT,
  model TEXT,
  connection_id TEXT,
  api_key_id TEXT,
  api_key_name TEXT,
  tokens_input BIGINT NOT NULL DEFAULT 0,
  tokens_output BIGINT NOT NULL DEFAULT 0,
  tokens_cache_read BIGINT NOT NULL DEFAULT 0,
  tokens_cache_creation BIGINT NOT NULL DEFAULT 0,
  tokens_reasoning BIGINT NOT NULL DEFAULT 0,
  service_tier TEXT NOT NULL DEFAULT 'standard',
  status TEXT,
  success INTEGER NOT NULL DEFAULT 1,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  ttft_ms INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  timestamp TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_uh_timestamp ON public.usage_history(timestamp);
CREATE INDEX IF NOT EXISTS idx_uh_provider ON public.usage_history(provider);
CREATE INDEX IF NOT EXISTS idx_uh_model ON public.usage_history(model);
CREATE INDEX IF NOT EXISTS idx_uh_service_tier ON public.usage_history(service_tier);

CREATE TABLE IF NOT EXISTS public.call_logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  method TEXT,
  path TEXT,
  status INTEGER,
  model TEXT,
  requested_model TEXT,
  provider TEXT,
  account TEXT,
  connection_id TEXT,
  duration BIGINT NOT NULL DEFAULT 0,
  tokens_in BIGINT NOT NULL DEFAULT 0,
  tokens_out BIGINT NOT NULL DEFAULT 0,
  tokens_cache_read BIGINT,
  tokens_cache_creation BIGINT,
  tokens_reasoning BIGINT,
  cache_source TEXT NOT NULL DEFAULT 'upstream',
  request_type TEXT,
  source_format TEXT,
  target_format TEXT,
  api_key_id TEXT,
  api_key_name TEXT,
  combo_name TEXT,
  combo_step_id TEXT,
  combo_execution_key TEXT,
  error_summary TEXT,
  detail_state TEXT NOT NULL DEFAULT 'none',
  artifact_relpath TEXT,
  artifact_size_bytes BIGINT,
  artifact_sha256 TEXT,
  has_request_body INTEGER NOT NULL DEFAULT 0,
  has_response_body INTEGER NOT NULL DEFAULT 0,
  has_pipeline_details INTEGER NOT NULL DEFAULT 0,
  request_summary TEXT
);
CREATE INDEX IF NOT EXISTS idx_cl_timestamp ON public.call_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_cl_status ON public.call_logs(status);
CREATE INDEX IF NOT EXISTS idx_call_logs_requested_model ON public.call_logs(requested_model);
CREATE INDEX IF NOT EXISTS idx_call_logs_request_type ON public.call_logs(request_type);
CREATE INDEX IF NOT EXISTS idx_cl_combo_target ON public.call_logs(combo_name, combo_execution_key, timestamp);

CREATE TABLE IF NOT EXISTS public.proxy_logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  status TEXT,
  proxy_type TEXT,
  proxy_host TEXT,
  proxy_port INTEGER,
  level TEXT,
  level_id TEXT,
  provider TEXT,
  target_url TEXT,
  public_ip TEXT,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  connection_id TEXT,
  combo_id TEXT,
  account TEXT,
  tls_fingerprint INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_pl_timestamp ON public.proxy_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_pl_status ON public.proxy_logs(status);
CREATE INDEX IF NOT EXISTS idx_pl_provider ON public.proxy_logs(provider);

CREATE TABLE IF NOT EXISTS public.domain_fallback_chains (
  model TEXT PRIMARY KEY,
  chain TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.domain_budgets (
  api_key_id TEXT PRIMARY KEY,
  daily_limit_usd DOUBLE PRECISION NOT NULL,
  monthly_limit_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  warning_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.8
);

CREATE TABLE IF NOT EXISTS public.domain_cost_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_key_id TEXT NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  timestamp BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dch_key ON public.domain_cost_history(api_key_id);
CREATE INDEX IF NOT EXISTS idx_dch_ts ON public.domain_cost_history(timestamp);

CREATE TABLE IF NOT EXISTS public.domain_lockout_state (
  identifier TEXT PRIMARY KEY,
  attempts TEXT NOT NULL,
  locked_until BIGINT
);

CREATE TABLE IF NOT EXISTS public.domain_circuit_breakers (
  name TEXT PRIMARY KEY,
  state TEXT NOT NULL DEFAULT 'CLOSED',
  failure_count INTEGER NOT NULL DEFAULT 0,
  last_failure_time BIGINT,
  options TEXT
);

CREATE TABLE IF NOT EXISTS public.semantic_cache (
  id TEXT PRIMARY KEY,
  signature TEXT NOT NULL UNIQUE,
  model TEXT NOT NULL,
  prompt_hash TEXT NOT NULL,
  response TEXT NOT NULL,
  tokens_saved BIGINT NOT NULL DEFAULT 0,
  hit_count BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sc_sig ON public.semantic_cache(signature);
CREATE INDEX IF NOT EXISTS idx_sc_model ON public.semantic_cache(model);

-- RLS keeps anonymous/public clients from reading these private operational
-- tables. The server-only service role bypasses RLS; never expose it to browsers.
ALTER TABLE public.provider_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.key_value ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.db_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proxy_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_fallback_chains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_cost_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_lockout_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domain_circuit_breakers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semantic_cache ENABLE ROW LEVEL SECURITY;
