-- OmniRoute PostgreSQL domain expansion.
-- Additive schema slice for the next migration phase; this is NOT the complete
-- SQLite schema and does not enable the PostgreSQL runtime. Domain modules must
-- be ported and tested before OMNIROUTE_STORAGE_BACKEND=postgres can be enabled.
--
-- Keep serialized timestamps/JSON as TEXT to match existing SQLite payloads.
-- SQLite AUTOINCREMENT becomes GENERATED BY DEFAULT AS IDENTITY.
-- SQLite-only WITHOUT ROWID and FTS5/vec virtual tables are not reproduced here.

ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS revoked_at TEXT;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS expires_at TEXT;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS last_used_at TEXT;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS key_prefix TEXT;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS ip_allowlist TEXT;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS scopes TEXT;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS disable_non_public_models INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS stream_default_mode TEXT NOT NULL DEFAULT 'legacy';
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS allowed_quotas TEXT NOT NULL DEFAULT '[]';
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS usage_limit_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS daily_usage_limit_usd DOUBLE PRECISION;
ALTER TABLE public.api_keys ADD COLUMN IF NOT EXISTS weekly_usage_limit_usd DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_api_keys_revoked_at ON public.api_keys(revoked_at);
CREATE INDEX IF NOT EXISTS idx_api_keys_expires_at ON public.api_keys(expires_at);

CREATE TABLE IF NOT EXISTS public.mcp_tool_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_name TEXT NOT NULL,
  input_hash TEXT,
  output_summary TEXT,
  duration_ms INTEGER,
  api_key_id TEXT,
  success INTEGER NOT NULL DEFAULT 1,
  error_code TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_mta_tool ON public.mcp_tool_audit(tool_name);
CREATE INDEX IF NOT EXISTS idx_mta_created ON public.mcp_tool_audit(created_at);
CREATE INDEX IF NOT EXISTS idx_mta_apikey ON public.mcp_tool_audit(api_key_id);

CREATE TABLE IF NOT EXISTS public.a2a_tasks (
  id TEXT PRIMARY KEY,
  state TEXT NOT NULL DEFAULT 'submitted',
  skill_id TEXT,
  input_json TEXT,
  output_json TEXT,
  cost_estimated DOUBLE PRECISION,
  cost_actual DOUBLE PRECISION,
  routing_explanation TEXT,
  resilience_trace TEXT,
  policy_verdict TEXT,
  api_key_id TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  completed_at TEXT,
  expires_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_a2a_state ON public.a2a_tasks(state);
CREATE INDEX IF NOT EXISTS idx_a2a_skill ON public.a2a_tasks(skill_id);
CREATE INDEX IF NOT EXISTS idx_a2a_created ON public.a2a_tasks(created_at);

CREATE TABLE IF NOT EXISTS public.a2a_task_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id TEXT NOT NULL REFERENCES public.a2a_tasks(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  data_json TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_a2ae_task ON public.a2a_task_events(task_id);
CREATE INDEX IF NOT EXISTS idx_a2ae_type ON public.a2a_task_events(event_type);

CREATE TABLE IF NOT EXISTS public.routing_decisions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id TEXT,
  task_type TEXT,
  combo_id TEXT,
  provider_selected TEXT,
  model_selected TEXT,
  score DOUBLE PRECISION,
  factors_json TEXT,
  fallbacks_triggered INTEGER NOT NULL DEFAULT 0,
  success INTEGER NOT NULL DEFAULT 1,
  latency_ms INTEGER,
  cost DOUBLE PRECISION,
  source TEXT NOT NULL DEFAULT 'api',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_rd_request ON public.routing_decisions(request_id);
CREATE INDEX IF NOT EXISTS idx_rd_combo ON public.routing_decisions(combo_id);
CREATE INDEX IF NOT EXISTS idx_rd_provider ON public.routing_decisions(provider_selected);
CREATE INDEX IF NOT EXISTS idx_rd_created ON public.routing_decisions(created_at);

CREATE TABLE IF NOT EXISTS public.combo_adaptation_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combo_id TEXT NOT NULL,
  provider_id TEXT NOT NULL,
  learned_score DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  request_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  avg_latency_ms DOUBLE PRECISION,
  last_failure_at TEXT,
  excluded_until TEXT,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  UNIQUE (combo_id, provider_id)
);
CREATE INDEX IF NOT EXISTS idx_cas_combo ON public.combo_adaptation_state(combo_id);

CREATE TABLE IF NOT EXISTS public.memories (
  id TEXT PRIMARY KEY,
  api_key_id TEXT NOT NULL,
  session_id TEXT,
  type TEXT NOT NULL CHECK (type IN ('factual', 'episodic', 'procedural', 'semantic')),
  "key" TEXT,
  content TEXT NOT NULL,
  metadata TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  expires_at TEXT,
  needs_reindex INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_memories_api_key ON public.memories(api_key_id);
CREATE INDEX IF NOT EXISTS idx_memories_session ON public.memories(session_id);
CREATE INDEX IF NOT EXISTS idx_memories_type ON public.memories(type);
CREATE INDEX IF NOT EXISTS idx_memories_expires ON public.memories(expires_at);
CREATE INDEX IF NOT EXISTS idx_memories_needs_reindex ON public.memories(needs_reindex) WHERE needs_reindex = 1;

CREATE TABLE IF NOT EXISTS public.skills (
  id TEXT PRIMARY KEY,
  api_key_id TEXT NOT NULL,
  name TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '1.0.0',
  description TEXT,
  "schema" TEXT NOT NULL,
  handler TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  mode TEXT NOT NULL DEFAULT 'auto',
  source_provider TEXT,
  tags TEXT,
  install_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_skills_api_key ON public.skills(api_key_id);
CREATE INDEX IF NOT EXISTS idx_skills_name ON public.skills(name);
CREATE INDEX IF NOT EXISTS idx_skills_mode ON public.skills(mode);
CREATE INDEX IF NOT EXISTS idx_skills_source_provider ON public.skills(source_provider);

CREATE TABLE IF NOT EXISTS public.skill_executions (
  id TEXT PRIMARY KEY,
  skill_id TEXT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
  api_key_id TEXT NOT NULL,
  session_id TEXT,
  input TEXT NOT NULL,
  output TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'success', 'error', 'timeout')),
  error_message TEXT,
  duration_ms INTEGER,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_skill_executions_skill ON public.skill_executions(skill_id);
CREATE INDEX IF NOT EXISTS idx_skill_executions_api_key ON public.skill_executions(api_key_id);
CREATE INDEX IF NOT EXISTS idx_skill_executions_status ON public.skill_executions(status);
CREATE INDEX IF NOT EXISTS idx_skill_executions_created ON public.skill_executions(created_at);

-- The SQLite status column was removed by a later migration, so it is omitted here.
CREATE TABLE IF NOT EXISTS public.files (
  id TEXT PRIMARY KEY,
  bytes BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  filename TEXT NOT NULL,
  purpose TEXT NOT NULL,
  content BYTEA,
  mime_type TEXT,
  api_key_id TEXT,
  deleted_at BIGINT,
  expires_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_files_api_key ON public.files(api_key_id);

CREATE TABLE IF NOT EXISTS public.batches (
  id TEXT PRIMARY KEY,
  endpoint TEXT NOT NULL,
  completion_window TEXT NOT NULL,
  status TEXT NOT NULL,
  input_file_id TEXT NOT NULL REFERENCES public.files(id),
  output_file_id TEXT REFERENCES public.files(id),
  error_file_id TEXT REFERENCES public.files(id),
  created_at BIGINT NOT NULL,
  in_progress_at BIGINT,
  expires_at BIGINT,
  finalizing_at BIGINT,
  completed_at BIGINT,
  failed_at BIGINT,
  expired_at BIGINT,
  cancelling_at BIGINT,
  cancelled_at BIGINT,
  request_counts_total INTEGER NOT NULL DEFAULT 0,
  request_counts_completed INTEGER NOT NULL DEFAULT 0,
  request_counts_failed INTEGER NOT NULL DEFAULT 0,
  metadata TEXT,
  api_key_id TEXT,
  errors TEXT,
  model TEXT,
  usage TEXT,
  output_expires_after_seconds INTEGER,
  output_expires_after_anchor TEXT
);
CREATE INDEX IF NOT EXISTS idx_batches_api_key ON public.batches(api_key_id);
CREATE INDEX IF NOT EXISTS idx_batches_status ON public.batches(status);

CREATE TABLE IF NOT EXISTS public.eval_runs (
  id TEXT PRIMARY KEY,
  run_group_id TEXT,
  suite_id TEXT NOT NULL,
  suite_name TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT,
  target_label TEXT NOT NULL,
  api_key_id TEXT,
  pass_rate INTEGER NOT NULL DEFAULT 0,
  total INTEGER NOT NULL DEFAULT 0,
  passed INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  avg_latency_ms INTEGER NOT NULL DEFAULT 0,
  summary_json TEXT NOT NULL,
  results_json TEXT NOT NULL,
  outputs_json TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_eval_runs_suite_created_at ON public.eval_runs(suite_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_eval_runs_group_id ON public.eval_runs(run_group_id);
CREATE INDEX IF NOT EXISTS idx_eval_runs_created_at ON public.eval_runs(created_at DESC);

CREATE TABLE IF NOT EXISTS public.eval_suites (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_eval_suites_updated_at ON public.eval_suites(updated_at DESC);

CREATE TABLE IF NOT EXISTS public.eval_cases (
  id TEXT PRIMARY KEY,
  suite_id TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  name TEXT NOT NULL,
  model TEXT,
  input_json TEXT NOT NULL,
  expected_strategy TEXT NOT NULL,
  expected_value TEXT,
  tags_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_eval_cases_suite_order ON public.eval_cases(suite_id, sort_order ASC, created_at ASC);

CREATE TABLE IF NOT EXISTS public.hourly_usage_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  date_hour TEXT NOT NULL,
  total_requests INTEGER NOT NULL DEFAULT 0,
  total_input_tokens INTEGER NOT NULL DEFAULT 0,
  total_output_tokens INTEGER NOT NULL DEFAULT 0,
  total_cost DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_hourly_usage_provider_model_date ON public.hourly_usage_summary(provider, model, date_hour);
CREATE INDEX IF NOT EXISTS idx_hourly_usage_date ON public.hourly_usage_summary(date_hour);

CREATE TABLE IF NOT EXISTS public.daily_usage_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  date TEXT NOT NULL,
  total_requests INTEGER NOT NULL DEFAULT 0,
  total_input_tokens INTEGER NOT NULL DEFAULT 0,
  total_output_tokens INTEGER NOT NULL DEFAULT 0,
  total_cost DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_daily_usage_provider_model_date ON public.daily_usage_summary(provider, model, date);
CREATE INDEX IF NOT EXISTS idx_daily_usage_date ON public.daily_usage_summary(date);

CREATE TABLE IF NOT EXISTS public.leaderboard (
  api_key_id TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'global',
  score INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (api_key_id, scope)
);
CREATE INDEX IF NOT EXISTS idx_leaderboard_scope_score ON public.leaderboard(scope, score DESC, api_key_id);

CREATE TABLE IF NOT EXISTS public.user_levels (
  api_key_id TEXT PRIMARY KEY,
  total_xp INTEGER NOT NULL DEFAULT 0,
  current_level INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS public.badge_definitions (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT,
  category TEXT,
  rarity TEXT NOT NULL DEFAULT 'common',
  criteria TEXT,
  hidden INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS public.user_badges (
  api_key_id TEXT NOT NULL,
  badge_id TEXT NOT NULL,
  unlocked_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (api_key_id, badge_id)
);
CREATE INDEX IF NOT EXISTS idx_user_badges_badge_id ON public.user_badges(badge_id);

CREATE TABLE IF NOT EXISTS public.xp_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_key_id TEXT NOT NULL,
  action TEXT NOT NULL,
  xp_earned INTEGER NOT NULL,
  metadata TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_xp_audit_log_api_key_created ON public.xp_audit_log(api_key_id, created_at);

CREATE TABLE IF NOT EXISTS public.token_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_api_key_id TEXT NOT NULL,
  to_api_key_id TEXT NOT NULL,
  amount INTEGER NOT NULL CHECK (amount > 0),
  reason TEXT,
  idempotency_key TEXT UNIQUE,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS public.invite_tokens (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  token_hash TEXT NOT NULL UNIQUE,
  created_by TEXT NOT NULL,
  used_by TEXT,
  server_url TEXT,
  max_uses INTEGER NOT NULL DEFAULT 1,
  use_count INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT,
  revoked_at TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_invite_tokens_code ON public.invite_tokens(code);
CREATE INDEX IF NOT EXISTS idx_invite_tokens_token_hash ON public.invite_tokens(token_hash);

CREATE TABLE IF NOT EXISTS public.community_servers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  api_key_hash TEXT NOT NULL,
  connected_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  last_sync_at TEXT,
  status TEXT NOT NULL DEFAULT 'connected' CHECK (status IN ('connected', 'disconnected', 'error')),
  error_message TEXT
);

CREATE TABLE IF NOT EXISTS public.session_model_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  combo_name TEXT NOT NULL,
  model_str TEXT NOT NULL,
  provider TEXT NOT NULL,
  connection_id TEXT,
  used_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_session_model_history_lookup ON public.session_model_history(session_id, combo_name, used_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_model_history_cleanup ON public.session_model_history(used_at);

CREATE TABLE IF NOT EXISTS public.cli_access_tokens (
  id TEXT PRIMARY KEY,
  token_hash TEXT NOT NULL UNIQUE,
  token_prefix TEXT NOT NULL,
  name TEXT NOT NULL,
  scope TEXT NOT NULL DEFAULT 'read',
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  last_used_at TEXT,
  expires_at TEXT,
  revoked_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_cli_access_tokens_hash ON public.cli_access_tokens(token_hash);

CREATE TABLE IF NOT EXISTS public.api_key_context_sources (
  api_key_id TEXT NOT NULL REFERENCES public.api_keys(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  token TEXT,
  base_url TEXT,
  vault_path TEXT,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  PRIMARY KEY (api_key_id, source_type)
);

CREATE TABLE IF NOT EXISTS public.memory_vec_meta (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  active_dim INTEGER,
  embedding_signature TEXT,
  last_reset_at TEXT,
  vec_loaded INTEGER NOT NULL DEFAULT 0
);
INSERT INTO public.memory_vec_meta (id, active_dim, embedding_signature, last_reset_at, vec_loaded)
VALUES (1, NULL, NULL, NULL, 0)
ON CONFLICT (id) DO NOTHING;

-- Server-side state is not exposed to anonymous/authenticated browser clients.
-- No direct-client policies are created here; service-role server access bypasses RLS.
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_tool_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.a2a_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.a2a_task_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routing_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.combo_adaptation_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skill_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_suites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hourly_usage_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_usage_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.badge_definitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.xp_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.token_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invite_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_model_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cli_access_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_key_context_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_vec_meta ENABLE ROW LEVEL SECURITY;
